# Generated by Django 5.1.7 on 2025-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_client", models.CharField(max_length=100)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_no", models.IntegerField()),
                ("address", models.TextField()),
            ],
        ),
    ]
